#!/bin/sh
### BEGIN INIT INFO
# Provides:          firstboot
# Required-Start:    $local_fs
# Required-Stop:
# Default-Start: 5
# Default-Stop:
# Short-Description: First boot script for FlightBox - resizes /root filesystem
# Description:
### END INIT INFO

. /lib/lsb/init-functions

case "$1" in
   start)
     log_daemon_msg "Starting firstboot" &&
     sleep 5 &&
     resizeP4 &&
     mount -o remount,rw / &&
     rm /etc/init.d/firstboot &&
     update-rc.d firstboot remove &&
     mount -o remount,ro / &&
     sleep 5 &&
     log_end_msg $?
     ;;
   *)
     echo "Usage: $0 start" >&2
     exit 3
     ;;
esac
